server.port=8080

spring.datasource.url=jdbc:postgresql://${APPOINTMENT_DB_HOST:appointment-db}:5432/appointmentdb
spring.datasource.username=postgres
spring.datasource.password=postgres

garage.service.base-url=${GARAGE_SERVICE_BASE_URL:http://localhost:8081}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
