services:
  garage-service:
    build:
      context: ./garage-service
      dockerfile: Dockerfile
    container_name: garage-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:h2:mem:garagedb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"

  appointment-service:
    build:
      context: ./car-appointment-service
      dockerfile: Dockerfile
    container_name: appointment-service
    ports:
      - "8080:8080"
    depends_on:
      - garage-service
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:h2:mem:appointmentdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      GARAGE_SERVICE_BASE_URL: http://garage-service:8081
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_SQL_INIT_MODE: always
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"